### ISSUE TITLE
Replacing a theme

### ISSUE THREAD

**Issue by 6r1d** [FlipperPA/wagtailcodeblock#18]
Hello, what is the proper way to extend wagtailcodeblock with other themes? For example, if I will download one of [these](https://github.com/PrismJS/prism-themes)? (I mostly want to use [FiraCode](https://github.com/tonsky/FiraCode) font for code.)

**Comment by FlipperPA** [comment]
Interesting, I had only supported the themes available on PrismJS because those were the only ones I knew of.

I'm currently swamped at work and another volunteer project, but I think you could get this working by:

- Edit `load_prism_theme` here to support full script URLs somehow: https://github.com/FlipperPA/wagtailcodeblock/blob/master/wagtailcodeblock/templatetags/wagtailcodeblock_tags.py#L18
- Edit `get_theme` here to pass that full URL to the theme through: https://github.com/FlipperPA/wagtailcodeblock/blob/master/wagtailcodeblock/settings.py#L23

Want to take a stab at it?

**Comment by 6r1d** [comment]
Thanks, then I will try to implement that next week.

**Comment by FlipperPA** [comment]
@6r1d A new version has been released to fix and majorly improve our asset pipeline. If we're still interested in adding other themes, we'll have to build a parallel system to include these. Let me know.

**Comment by 6r1d** [comment]
No, I don't need it right now, the project I used it for is closed now, but thanks for asking!
